### ISSUE TITLE
package directory 'webkit2png' does not exist

### ISSUE THREAD

**Issue by rfinquiron** [adamn/python-webkit2png#46]
I am trying to install using "Manual installation via Git" but getting this error

# python python-webkit2png/setup.py install
running install
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating webkit2png.egg-info
writing webkit2png.egg-info/PKG-INFO
writing top-level names to webkit2png.egg-info/top_level.txt
writing dependency_links to webkit2png.egg-info/dependency_links.txt
writing entry points to webkit2png.egg-info/entry_points.txt
writing manifest file 'webkit2png.egg-info/SOURCES.txt'
warning: manifest_maker: standard file 'setup.py' not found

error: package directory 'webkit2png' does not exist

Can somebody help me to install it ?

**Comment by nikitsaraf** [comment]
@rfinquiron There is an error in the instructions for "Manual installation via Git". 
Instead of `python python-webkit2png/setup.py install` in the fourth step, do the following

```
cd python-webkit2png/
python setup.py install
```

It should work ! Hope it would resolve the issue
