### ISSUE TITLE
Questions about usage

### ISSUE THREAD

**Issue by deronsizemore** [adamn/python-webkit2png#61]
Hi,

I came across this package as I'm wanting to be able to take a screenshot of a website from a URL and then extract a color palette from that image. I'm using django on a site now that already extracts color palettes from images, I just need the functionality so that I can take screenshots when a user enters a URL. Would I be able to do that with this package?

**Comment by troelskn** [comment]
Hi Deron.

Yes, in as much as you can make it work. The code isn't actively maintained, so you may run into some issues.
