### ISSUE TITLE
What license the project using

### ISSUE THREAD

**Issue by supersonictw** [adamn/python-webkit2png#69]
It not clear that it using whether GPL or LGPL(setup.py said)
even the version of license couldn't be found.

**Comment by Cybso** [comment]
Originally I've put a GPL notice into the source files. The setup file has been created afterwards, by @adamn I think. Regarding my parts of the code, feel free to re-license them under LGPL or BSD.

**Comment by Cybso** [comment]
Update: I found this in my outbox from 2010-03-09:

> Adam,
> 
> I've never heard about pyside project before, but it seems absolutly 
> possible to port webkit2png.py to it. As far as for the code written by 
> me I'm fine with re-licensing it under LGPL.
> 
> Regards,
> 
> Roland
> 
> 
> Am 09.03.10 15:46, schrieb Adam Nelson:
> > Roland,
> >
> > Do you have any response to this?  This guy wants to use the PySide
> > bindings to allow python-webkit2png to be LGPL.  Any thoughts?
> >
> > Regards,
> > Adam

**Comment by supersonictw** [comment]
OK, I understand.
Thank you for your reply
